services:
  db:
    image: postgres:16-alpine
    container_name: vetark_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vetark
      POSTGRES_USER: vetark
      POSTGRES_PASSWORD: vetark123
    ports:
      - "5433:5432"
    volumes:
      - vetark_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vetark_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vetark.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - vetark_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    build:
      context: ../../
      dockerfile: backend/docker/Dockerfile.dev
    container_name: vetark_backend
    restart: unless-stopped
    environment:
      PORT: 5000
      DATABASE_URL: postgres://vetark:vetark123@vetark_db:5432/vetark
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  vetark_db_data:
  vetark_pgadmin_data:
